# These settings are synced to GitHub by https://probot.github.io/apps/settings/
repository:
  name: spock-outputcapture
  description: OutputCapture for the Spock Framework
  topics: spock-extension, spock-framework, output-checking
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: false
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

branches:
- name: main
  protection:
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
    required_status_checks:
      strict: true
      contexts: []
    enforce_admins: false
    required_linear_history: true
    require_signed_commits: true
    restrictions:
      apps: []
      users: []
      teams: []
