name: build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: jdx/mise-action@v2
    - uses: gradle/actions/setup-gradle@v4
    - name: build
      run: ./gradlew check
      env:
        ASDF_DATA_DIR: /home/runner/.local/share/mise
